name: GenerateBlog

on: [issues]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [20]
    steps:
    - uses: actions/checkout@v4
    - name: Run a one-line script
      run: npx GenerateBlog --user yaoqs --repo Issues-LordYao
    - name: git commit
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout master
        git pull --ff
        git add _posts/*
        git commit -m "feat: github action generate blog"
    - name: git push
      run: |
        git push
