name: GenerateBlog

on: [issues,push]

jobs:
  build:
    runs-on: windows-latest #ubuntu-latest
    permissions:                # Job-level permissions configuration starts here
      contents: write           # 'write' access to repository contents
      pull-requests: write      # 'write' access to pull requests
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: ^20.11.0
    - name: npm
      continue-on-error: true
      run: |
        npm ci
        npm update
        npm i npm-check-updates -g --save
        ncu
        ncu -u
        npm ci
        # npm test
        node ./generateblog.js -u yaoqs -r Issues-LordYao -l blog
    - name: git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout main
        git pull --ff
        git add .
        git commit -m "feat: github action generate blog"
        git push
