name: GenerateBlog

on: [issues]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:                # Job-level permissions configuration starts here
      contents: write           # 'write' access to repository contents
      pull-requests: write      # 'write' access to pull requests
    strategy:
      matrix:
        node_version: [20]
    steps:
    - uses: actions/checkout@v4
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/cache@v4
    - name: npm
      run: |
        npm ci
        npm update
        npm ci npm-check-updates -g --save
        ncu
        ncu -u
        npm test
    - name: git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout master
        git pull --ff
        git add _posts/*
        git commit -m "feat: github action generate blog"
        git push
